### ISSUE TITLE
Handle multiple licenses for the same project

### ISSUE THREAD

**Issue by jonabc** [github/licensed#186]
I recently came across a case where a dependency was detected as both `mit` and `bsd-3-clause` which resulted in a classification of `other` and raised an error in `licensed status`.  However both of these license types were set as allowed in the configuration file, so there was no reason for this to be an error.

I'm wondering if it would be more appropriate then to store all detected license identifiers in  `.dep.yml` files and better support multi-licensed scenarios.

Some ideas off the top of my head

### 1. Store an array of licenses in a `license_keys`-like field

Storing multiple licenses in a new field and deprecating the `license` field would keep things backwards compatible and sane.  `licensed status` could be updated to check every `license_keys` entry if available, falling back to legacy behavior using `license` if unavailable.  

e.g.
```yaml
name: test
version: 1.0.0
license: other
license_keys: [mit, bsd-3-clause]
licenses:
- sources: LICENSE_MIT
   text: ...
- sources: LICENSE_BSD
   text: ...
```

The `licenses` key is already taken, but I'm sure there's something else that would make sense here to store all of the license keys found if `license_keys` is 👎 

The downside to this approach is that means potentially more in-depth manual examination and intervention if one of the multiple licenses is not detected properly, resulting in something like `[other, mit]`.

### 2. Include a `key` field on each `licenses` entry.

Adding a `key` field onto each entry in `licenses` more directly associates a license with each piece of text found.  `licensed status` would check all of these fields when available and default to the top level `license` field when unavailable.

As with the first option, the top level `license` field would be deprecated.

e.g.
```yaml
licenses:
- sources: LICENSE_MIT
   key: mit
   text: ...
- sources: LICENSE_BSD
   key: bsd-3-clause
   text: ...
```

The downside to this approach would be that the key data is a little harder to find for a human than a top level field, and the logic could be a little harder in deciding whether to check the deprecated `license` field vs the new `key` fields.

**Comment by jonabc** [comment]
@mlinksva what do you think about ☝️ in general, and the various proposals.  Do you have any other ideas of how to store and check multiple licenses for each dependency?

**Comment by mlinksva** [comment]
I think it's probably best to keep close to what licensee reports, which would be a mix of the two:

```yaml
name: test
version: 1.0.0
license: other
licenses:
- sources: LICENSE_MIT
   license: mit
   text: ...
- sources: LICENSE_BSD
   license: bsd-3-clause
   text: ...
```
Licensee doesn't know the relation of those different licenses so to reports NOASSERTION (other) for a project. [Eventually](https://github.com/licensee/licensee/issues/244) I'd like it to return a license expression (eg mit OR bsd-3-clause) if the project has metadata eg in a package manager file stating that is the relation. For the licensed use case though, you're right that if all of the detected licenses are in a configuration's approved list, licensed could pass a dependency even if there is no overall conclusion about the relation among those licenses for the dependency. This seems fine to me to have as licensed-specific logic.

**Comment by jonabc** [comment]
🤔 mixing the two would be confusing for users though.  Taking a different example

```yaml
name: test
version: 1.0.0
license: other
licenses:
- sources: LICENSE
   license: mit
   text: ...
- sources: README.md
   license: other
   text: |
     This project is covered by the MIT license.  Please see [LICENSE](./LICENSE) for full details.
```

In this case, should we expect users to fix the top level license field or the license sub-field on `README.md`?
