### ISSUE TITLE
Difference between ignored and reviewed

### ISSUE THREAD

**Issue by sergey-alekseev** [github/licensed#196]
Recently I got a question from my teammate:  
>What's the difference between `reviewed` and `ignored` in `.licensed.yml`?  

I found only [the following](https://github.com/github/licensed/blob/dd5eea2a94c7e0d27483476c24bd93d8501eaab0/docs/configuration.md#applications):  
```yaml
# These dependencies are explicitly ignored.
ignored:
  bundler:
    - some-internal-gem

  bower:
    - some-internal-package

# These dependencies have been reviewed.
reviewed:
  bundler:
    - bcrypt-ruby

  bower:
  - classlist # public domain
  - octicons
```

For me it's still not really clear when I should put a gem into `ignored:` and when into `reviewed:`. Can you guide me?  

Probably this should be clarified in the docs or combined into a single category to avoid confusions and save time debating with colleagues.

**Comment by mlinksva** [comment]
They do the same thing (@jonabc will correct me if that's not the case) but the use I've seen is like the example implies: ignored for internal dependencies, reviewed for external dependencies that aren't automatically allowed per the allowed list and license detection.

Ideally/wishlist I suppose they could have some different additional tooling, eg check whether a dependency can be moved out of approved and tests still pass, guardrails to detect whether something has changed that might merit a new review, or to detect whether a dependency really is internal.

**Comment by jonabc** [comment]
@sergey-alekseev @mlinksva 

`reviewed` is meant for dependencies that need to be cached and checked, but do not have a license found that matches the `allowed` configured licenses.

`ignored` is meant for dependencies that shouldn't be cached at all, and will not have cached metadata written to the repo.

Good question!  I'll update the docs when I have a chance, though I'd also welcome a PR :smile:

**Comment by sergey-alekseev** [comment]
Thanks for the clarification! @jonabc  
I copy-pasted your comments and made a PR to add the docs change to your to-do list.

**Comment by sergey-alekseev** [comment]
An interesting thing though. Chances are an external dependency doesn't have a license info (examples: https://github.com/iain/http_accept_language/issues/72, https://github.com/grosser/i18n_data/pull/47, https://github.com/grosser/sort_alphabetical/pull/23). If added to `reviewed` then `licensed status` fails with "missing license text". Hence they should be added to `ignored`. So I'm not sure whether "but do not have a license found that matches the `allowed` configured licenses." suits well for `reviewed` 🤔

**Comment by jonabc** [comment]
@sergey-alekseev what you described is intentional, though I'm not sure what the recommended remediation here is.  @mlinksva any thoughts?

**Comment by mlinksva** [comment]
I'd add (and recall having done this) some evidence for the reviewed status in the case no license text at all is extracted. In the case of the first example above, "Released under the MIT license" pulled from https://github.com/iain/http_accept_language/blob/74a6a244afa069154d08df0f5df373a6c7fc4fe2/README.md#with-bundler

Note https://github.com/github/licensed/issues/189 (depending on specific implementation) _could_ make this situation less common: in the case of the first example above again, https://github.com/iain/http_accept_language/blob/74a6a244afa069154d08df0f5df373a6c7fc4fe2/http_accept_language.gemspec#L13 would be recorded by licensed along with any license texts found.

**Comment by mlinksva** [comment]
Aside: thank you @sergey-alekseev for making PRs (seen from your examples, also thanks for providing concrete examples!) to improve licensing documentation from projects where it is missing, silently saving time for developers using (as they should) license tooling (licensed or numerous others) who might otherwise need to ask for review of innocuous dependencies.

**Comment by sergey-alekseev** [comment]
@mlinksva I probably didn't put enough emphasis on "missing license **text**". To make sure we are on the same page first let me clarify. `licensed cache` fetches licenses well for those examples. What's missing in these examples is **license text** (e.g. from a `LICENSE` file). See below:  
```
$ licensed status
Checking cached dependency records for project
..........F.F....................F...................
Errors:
* project.bundler.http_accept_language
  filename: project/.licenses/bundler/http_accept_language.dep.yml
    - missing license text

* project.bundler.i18n_data
  filename: project/.licenses/bundler/i18n_data.dep.yml
    - missing license text

* project.bundler.sort_alphabetical
  filename: project/.licenses/bundler/sort_alphabetical.dep.yml
    - missing license text


N dependencies checked, 3 errors found.
```

`project/.licenses/bundler/http_accept_language.dep.yml`:
```yaml
---
name: http_accept_language
version: 2.1.1
type: bundler
summary: Find out which locale the user preferes by reading the languages they specified
  in their browser
homepage: https://github.com/iain/http_accept_language
license: mit
licenses: []
notices: []
```

`project/.licenses/bundler/i18n_data.dep.yml`:
```yaml
---
name: i18n_data
version: 0.7.0
type: bundler
summary: country/language names and 2-letter-code pairs, in 85 languages
homepage: https://github.com/grosser/i18n_data
license: mit
licenses: []
notices: []
```

`project/.licenses/bundler/sort_alphabetical.dep.yml`:  
```yaml
---
name: sort_alphabetical
version: 1.1.0
type: bundler
summary: Sort UTF8 Strings alphabetical via Enumerable extension
homepage: https://github.com/grosser/sort_alphabetical
license: mit
licenses: []
notices: []
```

`project/.licensed.yml`:  
```yaml
sources:
  bundler: true

allowed:
  - mit

reviewed:
  bundler:
    - http_accept_language # no license file (see https://github.com/iain/http_accept_language/issues/72)
    - i18n_data # no license file (see https://github.com/grosser/i18n_data/pull/47)
    - sort_alphabetical # no license file (see https://github.com/grosser/sort_alphabetical/pull/23)
```

So if I understand correctly your proposal is to change `project/.licenses/bundler/http_accept_language.dep.yml` to the following:  
```yaml
name: http_accept_language
version: 2.1.1
type: bundler
summary: Find out which locale the user preferes by reading the languages they specified
  in their browser
homepage: https://github.com/iain/http_accept_language
license: mit
licenses:
- sources: README.md
  text: Released under the MIT license
notices: []
```

Am I correct?

Also I can fill in recently added license text for `project/.licenses/bundler/i18n_data.dep.yml` and `project/.licenses/bundler/sort_alphabetical.dep.yml` even though they didn't have that text at that version. Would that be fine in your view?
