### ISSUE TITLE
Enhancement request: allow multiple `apps` to be configured using wildcards

### ISSUE THREAD

**Issue by mhagger** [github/licensed#239]
I'm working with a Go project that builds multiple executables. In my case, the main files are arranged like

* `cmd/foo/main.go`
* `cmd/bar/main.go`
* `cmd/baz/main.go`
* …

, which is common in the Go world. Currently it seems that I have to list these `apps` individually, like

```
apps:
  - source_path: cmd/foo
  - source_path: cmd/bar
  - source_path: cmd/baz
  - …
```

Aside from being wordy, this seems error-prone. It's quite plausible that somebody might add another compilation target but forget to adjust the `.licensed.yml` file.

It would be nice if apps could be configured using wildcards, like

```
apps:
  - source_path: cmd/*
```

/cc @jonabc
