### ISSUE TITLE
Better detection of enabled sources in configuration file

### ISSUE THREAD

**Issue by jonabc** [github/licensed#28]
The configuration file can specify whether sources are enabled or disabled with settings like:
```
sources:
  rubygem: true
  go: false
  ...
```

Currently, if a source is not specified it will default to enabled.  A source can individually signal that it's not available via it's own `#enabled?` method, however a different paradigm on the configuration value may be a good idea.

Proposal:

I think the following set of rules would give users better flexibility in specifying which sources they want to run.
1. All sources are enabled via configuration when the `sources` configuration property is not set
2. All sources are enabled via configuration when the `sources` configuration property is empty
3. If any source is enabled via a `true` value, all sources without a `true` value are disabled
```yaml
sources:
  rubygem: true
  npm: false
  # go: false implicitly
```
4. If sources only contains `false` property values, all other sources are enabled
```yaml
sources:
  rubygem: false
  npm: false
  # go: true implicitly
```

The change here is in rule (3), where explicitly setting a `true` value implicitly disables all other sources.  This gives users the option of specifying only the sources they want to run without having to keep an expansive list of all sources that should not run.  It also keeps a good level of flexibility for users to not have to specify every source that should be enabled in every configuration file.
