### ISSUE TITLE
Does not seem to be picking up gems listed in `gems.rb`

### ISSUE THREAD

**Issue by ioquatix** [github/licensed#295]
I added the following config to [`async`](https://github.com/socketry/async):

```
sources:
  bundler: true
  npm: true

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
```

But the output of `bundle exec licensed cache` was empty, as well as other commands.

e.g.

```
% bundle exec licensed status
Checking cached dependency records for async

0 dependencies checked, 0 errors found.
```
