### ISSUE TITLE
Multi-package Go modules are not handled properly

### ISSUE THREAD

**Issue by AlekSi** [github/licensed#310]
It doesn't seem like licensed handles multi-package Go modules as a single unit, as it probably should. For example, consider this module:
* https://pkg.go.dev/mod/github.com/golang-migrate/migrate/v4@v4.12.2
* https://github.com/golang-migrate/migrate/tree/v4.12.2

It is a single version in a single repository with a single LICENSE file. But license treats all packages separately:
* https://github.com/percona-platform/licensed-test/tree/main/.github/licenses/cmd1/go/github.com/golang-migrate/migrate/v4

As a result, all packages should be listed individually:
```yaml
reviewed:
  go:
    - github.com/golang-migrate/migrate/v4
    - github.com/golang-migrate/migrate/v4/database
    - github.com/golang-migrate/migrate/v4/database/postgres
    - github.com/golang-migrate/migrate/v4/internal/url
    - github.com/golang-migrate/migrate/v4/source
```

* https://github.com/percona-platform/licensed-test/blob/f671da01726240eb8161298ff2c10144a717039c/.licensed.yml#L16-L22
