### ISSUE TITLE
Support patterns in the reviewed section

### ISSUE THREAD

**Issue by AlekSi** [github/licensed#311]
A quick fix for https://github.com/github/licensed/issues/310 could be a support for patterns in the `reviewed` section:
```yaml
reviewed:
  go:
    - github.com/golang-migrate/migrate/v4/**/*
```
