### ISSUE TITLE
Glob patterns not working as expected with reviewed Go packages  

### ISSUE THREAD

**Issue by julianvilas** [github/licensed#314]
The [docs](https://github.com/github/licensed/blob/master/docs/sources/go.md#reviewing-and-ignoring-all-packages-from-a-go-module) for Go sources indicate that glob patterns should work for both ignored and reviewed packages in the same way, but at least I was not able to make them work for reviewed packages.

Any idea of why?

I tried with different projects but the tests from below belong to [this repository](https://github.com/adevinta/security-overview/tree/licensed).
### Test Ignored

**conf**
```
source_path: "{.*,**/*}"
shared_cache: true
ignored:
  go:
    - github.mpi-internal.com/**/*
    - golang.org/x/**/*
allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
reviewed:
  go:
    - github.com/golang/freetype/raster
    - github.com/golang/freetype/truetype
    - github.com/russross/blackfriday/v2
    - github.com/jmespath/go-jmespath
    - github.com/AllenDang/simhash
```
**res**
```
$ licensed status
Checking cached dependency records for .
F....................................................
Errors:
* ..go.github.com/AllenDang/simhash
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/github.com/AllenDang/simhash.dep.yml
    - missing license text


53 dependencies checked, 1 errors found.
Checking cached dependency records for ..
...
```
### Test reviewed
**conf**
```
source_path: "{.*,**/*}"
shared_cache: true
ignored:
  go:
    - github.mpi-internal.com/**/*
allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
reviewed:
  go:
    - golang.org/x/**/*
    - github.com/golang/freetype/raster
    - github.com/golang/freetype/truetype
    - github.com/russross/blackfriday/v2
    - github.com/jmespath/go-jmespath
    - github.com/AllenDang/simhash
```
**res**
```
$ licensed status
Checking cached dependency records for .
F....................................................FFFFFF
Errors:
* ..go.github.com/AllenDang/simhash
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/github.com/AllenDang/simhash.dep.yml
    - missing license text

* ..go.golang.org/x/image/draw
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/golang.org/x/image/draw.dep.yml
    - license needs review: other

* ..go.golang.org/x/image/font
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/golang.org/x/image/font.dep.yml
    - license needs review: other

* ..go.golang.org/x/image/math/f64
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/golang.org/x/image/math/f64.dep.yml
    - license needs review: other

* ..go.golang.org/x/image/math/fixed
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/golang.org/x/image/math/fixed.dep.yml
    - license needs review: other

* ..go.golang.org/x/net/html
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/golang.org/x/net/html.dep.yml
    - license needs review: other

* ..go.golang.org/x/net/html/atom
  filename: /Users/julianvilas/go/src/github.com/adevinta/security-overview/.licenses/go/golang.org/x/net/html/atom.dep.yml
    - license needs review: other


59 dependencies checked, 7 errors found.
Checking cached dependency records for ..
...
```
