### ISSUE TITLE
license type "none" results in "missing license text" error

### ISSUE THREAD

**Issue by markphelps** [github/licensed#324]
See: https://github.com/markphelps/flipt/runs/1338656481
Code: https://github.com/markphelps/flipt/compare/ui-licenses

## Problem

Example License:

```
---
name: ansi-regex
version: 4.1.0
type: yarn
homepage: https://github.com/chalk/ansi-regex.git
license: none
licenses: []
notices: []
```

Running `licensed status`

Error:

```
Errors:
* ui.yarn.ansi-regex-4.1.0
  filename: /Users/markphelps/workspace/flipt/.licenses/ui/yarn/ansi-regex-4.1.0.dep.yml
    - missing license text
```

Also ran `licensed cache --force && licensed status` to no avail

## Expected Behavior

Licenses with type `none` would not return an error `missing license text` when running `licensed status`

**Comment by jonabc** [comment]
@markphelps I'm not sure this is a safe change to make as it removes a critical check in ensuring compliance.  In your branch you've set `none` as an allowed license type, I'm assuming to get CI to pass.  That solves the immediate failures but defeats the purpose of ensuring that all dependencies use allowed OSS licenses.

Licensed depends on all dependency packages being available locally in order to detect license contents.  In order for it to work properly in CI, you should add in steps before running licensed-ci in your licensed CI workflow
1. setup node
2. install yarn globally
3. run yarn to install dependencies for the project

I'm going to close this, but I'm happy to help you get your CI workflow passing.  Let me know how I can help.

**Comment by markphelps** [comment]
@jonabc , yes that would be great if you wouldnt mind helping

I tried to follow your suggestions locally to see if yarn would pull the dependencies locally, but it didnt seem to change anything:

```
$ npm install -g yarn --force
$ cd ui
$ yarn
yarn install v1.22.10
[1/6] 🔍  Validating package.json...
[2/6] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.54s.
$ git diff
[ no output ]
```

**Comment by jonabc** [comment]
@markphelps sorry for the delay.  I cloned your repo locally to take a look at the ui-licenses branch and I think you're running into https://github.com/github/licensed/issues/243.  I tried the [workaround](https://github.com/github/licensed/issues/243#issuecomment-594592514) in that issue, and licensed was able to find all dependency locations on disk using the npm source.  Note that this doesn't force you to use npm to manage your dependencies - try out the config below.

Along with removing `none` as an allowed license, I ended up with the following .licensed.yml config content which seemed to mostly work.  The nested `sources` config isn't entirely necessary, it saves a minor amount of calculation to determine what source applies to which app.

```yml
apps:
  - source_path: ./cmd/flipt
    cache_path: ./.licenses
    sources:
      go: true
  - source_path: ./ui
    cache_path: ./.licenses/ui
    sources:
      npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - mpl-2.0
  - unlicense

ignored:
  go:
    - github.com/markphelps/flipt/**/*
```
