### ISSUE TITLE
Licensed fails with XCRYPT_2.0 and GLIBC_2.29 not found

### ISSUE THREAD

**Issue by johlju** [github/licensed#337]
This error started today, yesterday `licensed` ran without issue. What dependency is missing on the build worker? 

Running a GitHub Action job like this.

```yaml
jobs:
  License:
    name: Valid licenses
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Licensed
      uses: jonabc/setup-licensed@v1
      with:
        version: 2.x
    - name: Install build dependencies
      run: |
        sudo npm install --global npm
        npm install
    - name: Licensed
      id: licensed
      run: |
        licensed version
```
Ends up with the following when running step id `licensed`:

```plaintext
licensed: /lib/x86_64-linux-gnu/libcrypt.so.1: version `XCRYPT_2.0' not found (required by licensed)
licensed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by licensed)
```

I tried adding the following but it did not help:

```
    - name: Install dependencies
      run: |
        sudo apt-get install cmake pkg-config
```

GitHub Actions job have this information for the build worker:

```
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20210131.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210131.1/images/linux/Ubuntu1804-README.md
```

Thank you for a great tool!
