### ISSUE TITLE
Missing 'review_changed_license` property on a changed dependency

### ISSUE THREAD

**Issue by andreas-hakansson-ingka** [github/licensed#442]
We are running Licenced 3.3.1 (but we've tried with 3.4.2 as well) in a Go project and one of our transient dependencies were updated and requires a re-review. However ,when we check in the cached record there is no `review_changed_license` property that we can remove as [mentioned in the documentation](https://github.com/github/licensed/blob/master/docs/commands/status.md#license-text-has-changed-and-needs-re-review-if-the-new-text-is-ok-remove-the-review_changed_license-flag-from-the-cached-record)

We have committed our license cache to sources control and run with the following `.licensed.yml` file

```yaml
sources:
  go: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - mit
  - unlicensed

reviewed:
  go:
    - github.com/jmespath/go-jmespath
    - github.com/klauspost/compress/**/*
    - github.com/google/**/*
    - golang.org/x/**/*
    - google.golang.org/**/*
```

It is the `github.com/klauspost/compress/` (transient) dependency that is causing us issues at the moment. If we rebuild the cache (without rebuilding it says it's too old and needs to be rebuilt, i.e we get `cached dependency record out of date` for several records) and run a status check then it says

```sh
Errors:
* [REDACTED]/klauspost/compress
  filename: /[REDACTED]/.licenses/go/github.com/klauspost/compress.dep.yml, version: v1.14.1, license: other, allowed: false
    - license needs review: other
```

The dependency updated from `v1.13.6` to `v1.14.1`.

I can see that it did change the cached record because I can commit a new copy of it to version control after rebuilding the cache. If I look at the cached record it contains this (I removed the actual license text to keep it short)

```yaml
---
name: github.com/klauspost/compress
version: v1.14.1
type: go
summary: 
homepage: https://pkg.go.dev/github.com/klauspost/compress
license: other
licenses:
- sources: LICENSE
  text: |
- sources: README.md
  text: This code is licensed under the same conditions as the original Go code. See
    LICENSE file.
notices: []
```

As you can see there's no `review_changed_license` property in there so, to be honest, we're not even sure how Licensed knows it needs to be reviewed again if we run `licensed status` more than once?

We are getting the same error on multiple machines
