### ISSUE TITLE
Detecting a wrong package name for scipy 1.9.2 installed by pip

### ISSUE THREAD

**Issue by kwkbtr** [github/licensed#550]
It seems that licensed detects a wrong package name for scipy 1.9.2.

The license file in the scipy package seems to be generated by combining [the license for scipy itself](https://github.com/scipy/scipy/blob/v1.9.2/LICENSE.txt) (BSD 3-clause) and [licenses for bundled libraries](https://github.com/scipy/scipy/blob/v1.9.2/tools/wheels/LICENSE_linux.txt).
You can find the actual license file (`scipy-1.9.2.dist-info/LICENSE.txt`) in the distribution package (a ZIP archive):
https://files.pythonhosted.org/packages/af/8e/552314ba91f257c2857d17f5a76dc21c63fe58a24634934cfecdd5eb56b2/scipy-1.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

When running `licensed cache` for scipy 1.9.2, it generates a cache file `GCC runtime library.dep.yml` with the following contents:

```yaml
---
name: GCC runtime library
version: 1.9.2
type: pip
summary: Fundamental algorithms for scientific computing in Python
homepage: https://scipy.org/
license: none
licenses: []
notices: []
```

The license file in the scipy package contains an entry for "GCC runtime library" as third entry of bundled libraries.
I have no idea how licensed picks it up and use its name for the cache file, but there may be two problems here:

- It looks like that licensed determines the name of the cache file from information in the license file. I guess it should instead use package information directly.
- Licensed might be failing to parse the first part of the scipy license file as a BSD 3-clause licensed. At a glance it looks like a normal BSD 3-clause license sentences.

**Comment by jonabc** [comment]
Thanks for the report!  I'll take a closer look at this during my daytime tomorrow (MST USA timezone) and try to set up a repro, but in the meantime can you provide any info about the following:
1. run `pip list` and see if `GCC runtime library` is listed as an installed package
1. run `pip show scipy` in your project and see if there is anything there related to the GCC runtime library dependency
1. is there a cached license metadata file for `scipy.dep.yml` with accurate information (name, version, licenses)?

**Comment by kwkbtr** [comment]
Thank you for a response!

> 1. run `pip list` and see if `GCC runtime library` is listed as an installed package

No, `GCC runtime library` doesn't show up in `pip list`, while `scipy` does.

> 2. run `pip show scipy` in your project and see if there is anything there related to the GCC runtime library dependency

`pip show scipy` displays the whole license text including the bundled libraries. There is nothing else related to the GCC runtime library.

> 3. is there a cached license metadata file for `scipy.dep.yml` with accurate information (name, version, licenses)?

No, `scipy.dep.yml` doesn't exist when installing scipy==1.9.2. When scipy==1.9.1 is installed, the following `scipy.dep.yml` is generated:

```yaml
---
name: scipy
version: 1.9.1
type: pip
summary: 'SciPy: Scientific Library for Python'
homepage: https://www.scipy.org
license: other
licenses:
- sources: LICENSE.txt
  text: [The whole license text]
notices: []
```
