### ISSUE TITLE
licenses (plural) key in gemspecs doesn't seem to be recognised?

### ISSUE THREAD

**Issue by dgmstuart** [github/licensed#567]
Most gems just specify a single license, but the gemspec format also supports specifying a list of licenses:

  https://guides.rubygems.org/specification-reference/#licenses=
  
It seems that these aren't recognised by licensed?

In particular the Ruby standard library gem stringio specifies `s.licenses = ["Ruby", "BSD-2-Clause"]`

  https://github.com/ruby/stringio/blob/master/stringio.gemspec
  
...but the cached license yml doesn't seem to use this, and instead only finds license information from the README:

```yaml
---
name: stringio
version: 3.0.1
type: bundler
summary: Pseudo IO on String
homepage: https://github.com/ruby/stringio
license: other
licenses:
- sources: README.md
  text: The gem is available as open source under the terms of the [2-Clause BSD License](https://opensource.org/licenses/BSD-2-Clause).
notices: []
```
